[package]
name = "deskstead"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
raylib = { git = "https://github.com/Cyphco/raylib-rs" }
winapi = { version = "0.3.9", features = ["winuser"] }
